# Sample configuration file for Anvil CLI
# 
# NOTE: This is the source of truth for the default configuration.
# When making changes to this file, copy it to internal/config/settings-sample.yaml
# so it gets embedded into the compiled binary.
#
# Command: cp assets/settings-sample.yaml internal/config/settings-sample.yaml

version: "{{APP_VERSION}}"
tools:
  required_tools:
  - git
  - curl
  installed_apps: []
groups:
  dev:
  - git
  - zsh
  - iterm2
  - visual-studio-code
  essentials:
  - slack
  - google-chrome
  - 1password
configs: {}
git:
  username: ""
  email: ""
  ssh_key_path: ""
github:
  config_repo: ""
  branch: main
  local_path: ""
  token_env_var: GITHUB_TOKEN
